export const LEARNING_TYPES = [
  'pattern',
  'phrasal_verb',
  'collocation',
  'idiom',
  'advanced_word',
  'technical_term',
];

export const TYPE_PRIORITY = {
  idiom: 0,
  pattern: 1,
  phrasal_verb: 2,
  collocation: 3,
  advanced_word: 4,
  technical_term: 5,
  named_entity: 6,
  phrase: 6,
  word: 7,
};

export const extractionConfig = {
  intensity: 50,
  userLevel: 'B2',
  maxItemsPerSubtitle: 2,
  maxItemsPerSubtitleLine: 2,
  realtimeMaxItemsPerLine: 2,
  exportMaxItemsPerLine: 4,
  maxStructureItemsPerLine: 1,
  maxVocabularyItemsPerLine: 1,
  playbackFriendlyMode: true,
  technicalMode: false,
  includeProperNouns: false,
  includeUiTerms: false,
  preferPatternsOverWords: true,
  minUsefulnessScore: 7,
  minStructureScore: 6,
  minAdvancedWordScore: 6,
  allowPatterns: true,
  allowIdioms: true,
  allowPhrasalVerbs: true,
  allowCollocations: true,
  allowAdvancedWords: true,
  allowTechnicalTerms: false,
  allowB2Words: true,
  allowProperNouns: false,
  compactDuringPlayback: true,
};

export const extractionQuota = {
  maxTotalPerSubtitle: 2,
  maxPatternsPerSubtitle: 1,
  maxAdvancedWordsPerSubtitle: 1,
  minTotalPerSubtitle: 1,
  allowAdvancedWords: true,
};

export const LEVEL_ORDER = {
  A1: 1,
  A2: 2,
  B1: 3,
  B2: 4,
  C1: 5,
  C2: 6,
};

export const GLUED_TOKEN_REPAIRS = [
  { pattern: /\bshouldn'thave\b/gi, replacement: "shouldn't have" },
  { pattern: /\bcouldn'thave\b/gi, replacement: "couldn't have" },
  { pattern: /\bdon'thave\b/gi, replacement: "don't have" },
  { pattern: /\bcan'thave\b/gi, replacement: "can't have" },
  { pattern: /\bbestif\b/gi, replacement: 'best if' },
  { pattern: /\byouhave\b/gi, replacement: 'you have' },
  { pattern: /\bflyingand\b/gi, replacement: 'flying and' },
];

export const SIMPLE_WORDS = new Set([
  'a',
  'air',
  'all',
  'and',
  'are',
  'ask',
  'asked',
  'be',
  'believe',
  'best',
  'can',
  'come',
  'came',
  'could',
  'do',
  'does',
  'did',
  'earth',
  'feature',
  'features',
  'escape',
  'escaped',
  'family',
  'fire',
  'function',
  'image',
  'item',
  'get',
  'go',
  'good',
  'great',
  'have',
  'help',
  'him',
  'i',
  'it',
  'know',
  'leave',
  'let',
  'library',
  'like',
  'look',
  'magic',
  'make',
  'made',
  'must',
  'need',
  'needed',
  'needs',
  'own',
  'save',
  'saved',
  'see',
  'take',
  'the',
  'think',
  'this',
  'to',
  'tool',
  'tribe',
  'village',
  'want',
  'wanted',
  'water',
  'way',
  'web',
  'you',
  'your',
]);

export const AUXILIARY_OR_NEGATION = new Set([
  'am',
  'are',
  'be',
  'been',
  'being',
  'can',
  "can't",
  'could',
  "couldn't",
  'did',
  "didn't",
  'do',
  "don't",
  'does',
  "doesn't",
  'had',
  "hadn't",
  'has',
  "hasn't",
  'have',
  "haven't",
  'is',
  "isn't",
  'must',
  "mustn't",
  'not',
  'should',
  "shouldn't",
  'was',
  "wasn't",
  'were',
  "weren't",
  'will',
  "won't",
  'would',
  "wouldn't",
]);

export const COMMON_NAMED_ENTITIES = new Set([
  'aang',
  'air nomads',
  'airbender',
  'fire nation',
  'katara',
  'netflix',
  'obsidian',
  'sokka',
  'water tribe',
  'youtube',
]);

export const UI_TERMS = new Set([
  'add to excalidraw',
  'add to library',
  'browse libraries',
  'command palette',
  'miscellaneous features',
  'open library',
  'plugin settings',
]);

export const PRODUCT_TERMS = new Set([
  'excalidraw',
  'netflix',
  'obsidian',
  'youtube',
]);

export const TECHNICAL_TERMS = new Set([
  'command palette',
  'context menu',
  'element properties panel',
  'ocr',
  'plugin settings',
  'simple illustrations',
  'stencil library',
]);

export const LOW_VALUE_SURFACE_WORDS = new Set([
  'button',
  'clipboard',
  'color',
  'download',
  'enabled',
  'feature',
  'features',
  'function',
  'image',
  'item',
  'keyboard',
  'library',
  'object',
  'objects',
  'palette',
  'placed',
  'powerful',
  'result',
  'shape',
  'tool',
  'web',
]);

export const FRAGMENT_PATTERNS = [
  /^(?:couldn't|don't|didn't|can't|won't|wouldn't|shouldn't)\s+\w+$/i,
  /^(?:he's|she's|it's|they're|we're|you're|are|is|was|were)\s+\w+$/i,
  /^(?:can|could|will|would|should|must)\s+\w+$/i,
  /^from\s+(?:our|your|my|the)\s+\w+$/i,
  /^(?:the|a|an)\s+\w+(?:\s+\w+)?$/i,
];

export const STRUCTURE_VALUE_ALLOWLIST = new Set([
  'let sb do sth',
  'make sb do sth',
  'help sb do sth',
  'used to do sth',
  "it's best if ...",
  'run sth from somewhere',
  'be placed on sth',
  'be enabled in sth',
  'position A relative to B',
  'relative to sth',
  'not work with sth',
  'visual thinking',
]);

export const NORMALIZATION_RULES = [
  {
    id: 'let-sb-do-sth',
    type: 'pattern',
    expression: 'let sb do sth',
    difficulty: 'B1',
    pattern: /\b(?:(?:do|don't|did|didn't|couldn't|could|can|can't|won't|will|wouldn't|would|please|to)\s+)*let(?:s)?\s+(?:[a-z][a-z'-]*|[A-Z][a-z'-]*)\s+[a-z][a-z'-]*(?:\s+(?!(?:that|who|which|where|when|and|but)\b)[^.!?\s]+){0,6}/i,
    meaning_zh: "让某人做某事；否定形式为 don't let sb do sth，表示不要让某人做某事",
    structure: 'let + object + bare infinitive',
    why_useful: '高频使役结构，可替换宾语和动词来表达允许、阻止或要求。',
    example_zh: '奶奶，拜托，不要让索卡做这件事。',
  },
  {
    id: 'run-sth-from-somewhere',
    type: 'pattern',
    expression: 'run sth from somewhere',
    difficulty: 'B2',
    pattern: /\brun\s+(?:it|this|that|them|[a-z][a-z'-]*)\s+from\s+.+?(?=\s+and\b|[.!?]|$)/i,
    meaning_zh: '从某处运行某物',
    structure: 'run + object + from + place/source',
    why_useful: 'run from 是可迁移的动词加介词结构，可替换运行对象和来源位置。',
    example_zh: '你可以从命令面板运行它。',
  },
  {
    id: 'be-placed-on-sth',
    type: 'pattern',
    expression: 'be placed on sth',
    difficulty: 'B2',
    pattern: /\b(?:be\s+|is\s+|are\s+|was\s+|were\s+|will\s+be\s+)?placed\s+on\s+[^.!?]+/i,
    meaning_zh: '被放置到某处 / 被保存到某处',
    structure: 'be + past participle + on + noun',
    why_useful: '被动语态加介词 on 的常用结构，比单词 placed 更有学习价值。',
    example_zh: '结果会被放到剪贴板上。',
  },
  {
    id: 'position-a-relative-to-b',
    type: 'pattern',
    expression: 'position A relative to B',
    difficulty: 'B2',
    pattern: /\bposition\s+[^.!?]+\s+relative\s+to\s+[^.!?]+/i,
    meaning_zh: '相对于 B 定位 A',
    structure: 'position + object + relative to + reference',
    why_useful: 'position 和 relative to 搭配表达参照关系，适合迁移到技术和日常说明。',
    example_zh: '它让你相对于其他元素定位对象。',
  },
  {
    id: 'relative-to-sth',
    type: 'pattern',
    expression: 'relative to sth',
    difficulty: 'B2',
    pattern: /\brelative\s+to\s+[^.!?]+/i,
    meaning_zh: '相对于某物',
    structure: 'relative to + noun',
    why_useful: 'relative to 是高频介词搭配，中文学习者容易漏掉 to。',
    example_zh: '相对于其他元素。',
  },
  {
    id: 'be-enabled-in-sth',
    type: 'pattern',
    expression: 'be enabled in sth',
    difficulty: 'B2',
    pattern: /\b(?:be\s+|is\s+|are\s+|was\s+|were\s+)?enabled\s+in\s+[^.!?]+/i,
    meaning_zh: '在某处被启用',
    structure: 'be + past participle + in + noun',
    why_useful: '被动语态加 in 表示功能启用位置，优于单独 enabled。',
    example_zh: 'OCR 在插件设置中启用。',
  },
  {
    id: 'not-work-with-sth',
    type: 'pattern',
    expression: 'not work with sth',
    difficulty: 'B2',
    pattern: /\b(?:does\s+not|doesn't|do\s+not|don't|will\s+not|won't|not)\s+work\s+with\s+[^.!?]+/i,
    meaning_zh: '不能与某物配合使用；不兼容某物',
    structure: 'not + work + with + noun',
    why_useful: 'work with 在否定兼容场景中高频，可替换对象。',
    example_zh: '这个按钮不能与 Obsidian 配合使用。',
  },
  {
    id: 'one-of-plural',
    type: 'pattern',
    expression: 'one of + plural noun / pronoun',
    difficulty: 'B2',
    pattern: /\bone\s+of\s+(?:them|us|those|these|the\s+[a-z][a-z'-]+s)\b/i,
    meaning_zh: '……之一',
    structure: 'one of + plural noun/pronoun',
    why_useful: 'one of 后接复数名词或复数代词，是常见易错结构。',
    example_zh: '网格就是其中之一。',
  },
  {
    id: 'protect-sb-from-sth',
    type: 'pattern',
    expression: 'protect sb from sth',
    difficulty: 'B2',
    pattern: /\bprotect(?:ing|s|ed)?\s+(?:me|you|him|her|us|them|[a-z][a-z'-]*)\s+from\s+[^.!?]+/i,
    meaning_zh: '保护某人免受某事伤害',
    structure: 'protect + object + from + noun',
    why_useful: '比单个 protect 更可迁移，常用于说明保护对象和风险来源。',
    example_zh: '我在保护你免受威胁。',
  },
  {
    id: 'look-forward-to',
    type: 'pattern',
    expression: 'look forward to sth / doing sth',
    difficulty: 'B2',
    pattern: /\b(?:not\s+)?look(?:ing|s|ed)?\s+forward\s+to\s+[^.!?]+/i,
    meaning_zh: '期待某事 / 期待做某事',
    structure: 'look forward to + noun / gerund',
    why_useful: 'to 在这里是介词，后接名词或动名词，是常见易错结构。',
    example_zh: '我并不期待那件事。',
  },
  {
    id: 'choose-a-over-b',
    type: 'pattern',
    expression: 'choose A over B',
    difficulty: 'B2',
    pattern: /\bchoos(?:e|es|ing)|\bchose\b/i,
    surfacePattern: /\b(?:choose|chooses|choosing|chose)\s+[^.!?]+\s+over\s+[^.!?]+/i,
    meaning_zh: '在 B 和 A 之间选择 A；选择 A 而不是 B',
    structure: 'choose + A + over + B',
    why_useful: '表达取舍和优先级，比单独 choose 更有句型价值。',
    example_zh: '你真的会选择他而不是你的部落吗？',
  },
  {
    id: 'its-best-if',
    type: 'pattern',
    expression: "it's best if ...",
    difficulty: 'B1',
    pattern: /\bit(?:'s| is)\s+best\s+if\s+[^.!?]+/i,
    meaning_zh: '最好是……；如果……会比较好',
    structure: "it is best if + clause",
    why_useful: '用于委婉提出建议或安排，结构完整且可替换从句。',
    example_zh: '我觉得气宗男孩最好离开。',
  },
  {
    id: 'convert-a-into-b',
    type: 'pattern',
    expression: 'convert A into B',
    difficulty: 'B2',
    pattern: /\bconvert\s+.+?\s+into\s+[^.!?]+/i,
    meaning_zh: '把 A 转换成 B；使 A 变成 B',
    structure: 'convert + object + into + result',
    why_useful: 'convert into 是高频转换结构，比单独 convert 更有迁移价值。',
    example_zh: '它会把 Obsidian.md 毛毛虫变成美丽的蝴蝶。',
  },
  {
    id: 'visual-thinking',
    type: 'collocation',
    expression: 'visual thinking',
    difficulty: 'B2',
    pattern: /\bvisual\s+thinking\b/i,
    meaning_zh: '视觉化思考；视觉思维',
    structure: 'adjective + noun collocation',
    why_useful: '常用于学习、设计和白板工具语境，整体搭配比逐词更有价值。',
  },
  {
    id: 'under-the-disguise',
    type: 'collocation',
    expression: 'under the disguise',
    difficulty: 'B2',
    pattern: /\bunder\s+the\s+disguise\b/i,
    meaning_zh: '在伪装之下；以……为掩饰',
    structure: 'under + the + noun',
    why_useful: 'disguise 和介词 under 组合后有非字面含义，适合整体记忆。',
  },
  {
    id: 'scratch-the-surface',
    type: 'idiom',
    expression: 'scratch the surface',
    difficulty: 'B2',
    pattern: /\bscratch(?:ing|es|ed)?\s+the\s+surface\b/i,
    meaning_zh: '只触及表面；浅尝辄止',
    structure: 'scratch + the + surface',
    why_useful: '常见习语，不能按 scratch 和 surface 逐词理解。',
  },
  {
    id: 'fast-paced',
    type: 'advanced_word',
    expression: 'fast-paced',
    difficulty: 'B2',
    pattern: /\bfast[-\s]+paced\b/i,
    meaning_zh: '节奏很快的；快节奏的',
    structure: 'adjective; a fast-paced lecture/demo',
    why_useful: '常用于描述视频、课程、工作环境的节奏。',
  },
  {
    id: 'come-between-a-and-b',
    type: 'phrasal_verb',
    expression: 'come between A and B',
    difficulty: 'B2',
    pattern: /\bcome\s+between\s+[^.!?]+\s+and\s+[^.!?]+/i,
    meaning_zh: '介入、妨碍 A 和 B 的关系',
    structure: 'come between + A + and + B',
    why_useful: '短语动词带固定介词框架，常用于关系冲突。',
  },
  {
    id: 'ask-for',
    type: 'phrasal_verb',
    expression: 'ask for',
    difficulty: 'B2',
    pattern: /\bask(?:s|ed|ing)?\s+for\b/i,
    meaning_zh: '请求；要求得到',
    structure: 'ask for + noun',
    why_useful: '高频短语动词，宾语位置固定。',
  },
  {
    id: 'add-to-sth',
    type: 'phrasal_verb',
    expression: 'add to sth',
    difficulty: 'B2',
    pattern: /\badd\s+to\s+[^.!?]+/i,
    meaning_zh: '添加到某物；增加某物',
    structure: 'add to + noun',
    why_useful: 'add to 是常用短语动词，介词 to 固定。',
  },
  {
    id: 'get-out',
    type: 'idiom',
    expression: 'get out',
    difficulty: 'B2',
    pattern: /\bget\s+out\b/i,
    meaning_zh: '出去；别开玩笑；快走',
    structure: 'get out',
    why_useful: '语境中常有非字面或口语命令含义。',
  },
  {
    id: 'my-fault',
    type: 'idiom',
    expression: "it's my fault",
    difficulty: 'B2',
    pattern: /\bit(?:'s| is)\s+my\s+fault\b/i,
    meaning_zh: '是我的错',
    structure: "it's + possessive + fault",
    why_useful: '常见责任表达，可替换物主代词。',
  },
  {
    id: 'i-knew-it',
    type: 'idiom',
    expression: 'I knew it',
    difficulty: 'B2',
    pattern: /\bi\s+knew\s+it\b/i,
    meaning_zh: '我就知道；果然如此',
    structure: 'I knew it',
    why_useful: '常见口语反应，整体意义强于逐词理解。',
  },
  {
    id: 'come-on',
    type: 'idiom',
    expression: 'come on',
    difficulty: 'B2',
    pattern: /\bcome\s+on\b/i,
    meaning_zh: '拜托；快点；得了吧',
    structure: 'come on',
    why_useful: '口语高频，含义依赖语境，不宜逐词翻译。',
  },
];

export const ADVANCED_WORDS = {
  activate: {
    expression: 'activate',
    difficulty: 'B2',
    meaning_zh: '激活；启用',
    structure: 'verb; activate sth / activate sth with sth',
    why_useful: '教程和说明中高频，重点在宾语和方式搭配。',
  },
  align: {
    expression: 'align',
    difficulty: 'B2',
    meaning_zh: '对齐；使一致',
    structure: 'verb; align sth with sth',
    why_useful: '技术说明和抽象表达都常用，介词 with 容易漏。',
  },
  banish: {
    expression: 'banish',
    difficulty: 'C1',
    meaning_zh: '放逐；驱逐',
    structure: 'verb; banish sb from somewhere',
    why_useful: '中高级叙事词，常用于惩罚、流放语境。',
  },
  confess: {
    expression: 'confess',
    difficulty: 'C1',
    meaning_zh: '承认；坦白',
    structure: 'verb; confess to sth / confess that ...',
    why_useful: '常见于剧情、法律和心理表达。',
  },
  forbidden: {
    expression: 'forbidden',
    difficulty: 'C1',
    meaning_zh: '被禁止的；禁忌的',
    structure: 'adjective; forbidden to do sth / forbidden from doing sth',
    why_useful: '比 banned 更书面，搭配有学习价值。',
  },
  threat: {
    expression: 'threat',
    difficulty: 'C1',
    meaning_zh: '威胁；可能造成伤害的人或事',
    structure: 'noun; threat to sb/sth; protect sb from threats',
    why_useful: '常与 danger/risk 区分，并参与高价值搭配。',
  },
  threats: {
    expression: 'threat',
    difficulty: 'C1',
    meaning_zh: '威胁；可能造成伤害的人或事',
    structure: 'noun; threat to sb/sth; protect sb from threats',
    why_useful: '常与 danger/risk 区分，并参与高价值搭配。',
  },
  traitor: {
    expression: 'traitor',
    difficulty: 'C1',
    meaning_zh: '叛徒',
    structure: 'noun; a traitor to sb/sth',
    why_useful: '剧情中常见的中高级人物评价词。',
  },
  vanish: {
    expression: 'vanish',
    difficulty: 'C1',
    meaning_zh: '消失；突然不见',
    structure: 'verb; vanish from sight / vanish into thin air',
    why_useful: '比 disappear 更有画面感和叙事色彩。',
  },
  convert: {
    expression: 'convert',
    difficulty: 'B2',
    meaning_zh: '转换；转变',
    structure: 'verb; convert A into B',
    why_useful: '常用于技术和抽象变化，重点搭配 into。',
  },
  customize: {
    expression: 'customize',
    difficulty: 'B2',
    meaning_zh: '定制；按需求调整',
    structure: 'verb; customize sth for sb/sth',
    why_useful: '软件和工作流语境常见，比 change 更精确。',
  },
  demonstrate: {
    expression: 'demonstrate',
    difficulty: 'B2',
    meaning_zh: '演示；证明',
    structure: 'verb; demonstrate how/that ...',
    why_useful: '教程、演讲和论证中高频，搭配有学习价值。',
  },
  demonstration: {
    expression: 'demonstration',
    difficulty: 'B2',
    meaning_zh: '演示；示范',
    structure: 'noun; a demonstration of sth',
    why_useful: '教程类字幕高频，比 demo 更正式。',
  },
  'fast paced': {
    expression: 'fast-paced',
    difficulty: 'B2',
    meaning_zh: '节奏很快的；快节奏的',
    structure: 'adjective; a fast-paced lecture/demo',
    why_useful: '常用于描述视频、课程、工作环境的节奏。',
  },
  disguise: {
    expression: 'disguise',
    difficulty: 'B2',
    meaning_zh: '伪装；掩饰',
    structure: 'noun/verb; in disguise / disguise sth as sth',
    why_useful: '常用于“表面看起来像 X，实则是 Y”的表达。',
  },
  intelligently: {
    expression: 'intelligently',
    difficulty: 'B2',
    meaning_zh: '智能地；明智地',
    structure: 'adverb; intelligently + verb',
    why_useful: '技术说明中常用于描述系统自动判断或处理方式。',
  },
  miscellaneous: {
    expression: 'miscellaneous',
    difficulty: 'C1',
    meaning_zh: '各种各样的；混杂的',
    structure: 'adjective; miscellaneous items/features',
    why_useful: '常见于分类标题和说明，拼写和含义都值得掌握。',
  },
  modify: {
    expression: 'modify',
    difficulty: 'B2',
    meaning_zh: '修改；调整',
    structure: 'verb; modify sth / modify sth to do sth',
    why_useful: '比 change 更正式，常用于软件、文档和规则。',
  },
  powerhouse: {
    expression: 'powerhouse',
    difficulty: 'C1',
    meaning_zh: '强大的事物；实力强者',
    structure: 'noun; a creative/productivity powerhouse',
    why_useful: '非字面比喻词，常用于评价工具或组织能力。',
  },
  relative: {
    expression: 'relative',
    difficulty: 'B2',
    meaning_zh: '相对的；相关的',
    structure: 'adjective; relative to sth',
    why_useful: '常和 to 搭配，表达参照关系。',
  },
  revolutionary: {
    expression: 'revolutionary',
    difficulty: 'C1',
    meaning_zh: '革命性的；带来重大变革的',
    structure: 'adjective; a revolutionary idea/tool',
    why_useful: '高频评价词，比 good/powerful 更精确。',
  },
  scribble: {
    expression: 'scribble',
    difficulty: 'B2',
    meaning_zh: '潦草地写；涂写',
    structure: 'verb/noun; scribble a note / a quick scribble',
    why_useful: '视觉笔记和手写场景常见，含义比 write 更具体。',
  },
  attribute: {
    expression: 'attribute',
    difficulty: 'C1',
    meaning_zh: '属性；把……归因于',
    structure: 'noun/verb; an attribute of sth / attribute sth to sth',
    why_useful: '技术和学术语境常见，词性和搭配都值得学习。',
  },
};
